apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    {{- include "crystaltwin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
  selector:
    {{- include "crystaltwin.selectorLabels" . | nindent 4 }}
